env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'react-hooks'
  - 'promise'
  - 'import'
rules:
  {}
globals:
  React: 'readonly'
  JSX: 'readonly'
  NodeJS: 'readonly'
ignorePatterns: ['src/assets/*']
