env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'react-hooks'
  - 'promise'
  - 'import'
rules:
  {
    semi: off,
    space-before-function-paren: off,
    comma-dangle: off,
    curly: off,
    no-use-before-define: off,
    react/react-in-jsx-scope: off,
    multiline-ternary: off,
    no-async-promise-executor: off,
    no-console: off,
    no-trailing-spaces: off,
    no-unused-vars: off,
    space-infix-ops: off,
    no-extra-boolean-cast: off,
    indent: off,
    no-floating-decimal: off,
    no-multi-spaces: off,
    quotes: off, 
    prefer-const: off,
    spaced-comment: off,
    no-multiple-empty-lines: off,
    padded-blocks: off,
    array-callback-return: off,
    comma-spacing: off,
    no-unneeded-ternary: off,
  }
globals:
  React: 'readonly'
  JSX: 'readonly'
  NodeJS: 'readonly'
ignorePatterns: ['src/assets/*']
